# Generated by Django 5.2.4 on 2025-07-28 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_course_lecturer_alter_course_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='clarity_rating',
            field=models.PositiveSmallIntegerField(help_text="Rate the clarity of the lecturer's explanations (1–5)"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='effectiveness_rating',
            field=models.PositiveSmallIntegerField(help_text='Rate the overall effectiveness of the course (1–5)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='engagement_rating',
            field=models.PositiveSmallIntegerField(help_text="Rate the lecturer's ability to engage the class (1–5)"),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
