# Generated by Django 5.2.4 on 2025-07-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
