# Generated by Django 5.2.4 on 2025-07-28 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_lecturer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
